# Dockerfile MSGFPlus

FROM openjdk:latest
MAINTAINER DavidJM <biodavidjm@gmail.com>
RUN yum install -y git
RUN yum install -y wget
RUN yum install -y unzip

RUN wget -P /app/ https://github.com/MSGFPlus/msgfplus/releases/download/v2020.03.14/MSGFPlus_v20200314.zip
RUN cd /app/ && unzip MSGFPlus_v20200314.zip

